version: '3'
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  scraper:
    image: lab_scraper

  parser:
    image: lab_parser

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  db_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data_volume:

